export const COVER_IMAGE_MAX_BYTES = 2 * 1024 * 1024
export const COVER_UPLOAD_REQUEST_OVERHEAD_BYTES = 128 * 1024
export const COVER_UPLOAD_MAX_REQUEST_BYTES = COVER_IMAGE_MAX_BYTES + COVER_UPLOAD_REQUEST_OVERHEAD_BYTES

export const COVER_SIZE_ERROR_MESSAGE = '画像サイズは2MB以下にしてください。'
export const COVER_UPLOAD_REQUEST_SIZE_ERROR_MESSAGE = 'アップロードサイズが大きすぎます（2MB以下）。'
